services:

  tsn-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: worker
    environment:
      - QUARKUS_PROFILE=worker
    restart: always

  tsn-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: worker
    environment:
      - QUARKUS_PROFILE=worker
    restart: always

  tsn-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: gateway
    environment:
      - QUARKUS_PROFILE=gateway
      - TSN_WORKER_URLS=http://tsn-worker-1:8080,http://tsn-worker-2:8080
    ports:
      - "8080:8080"
    depends_on:
      - tsn-worker-1
      - tsn-worker-2
    restart: always
