# === Gateway profile ===
%gateway.tsn.worker.urls=http://localhost:8080

# === Worker profile ===
%worker.tsn.worker.urls=http://localhost:8080

# === Dev profile (roda tudo local) ===
%dev.tsn.worker.urls=http://localhost:8080

# === Default (fallback) ===
tsn.worker.urls=http://localhost:8080
